skillset_inview.settings:
  type: config_object
  label: 'Skillset Inview Config'
  nullable: TRUE
  translatable: true
  mapping:
    heading:
      type: text
      label: 'Skillset section display header'
    color-active:
      type: integer
      label: 'Use Config for Skillbar colors.  effect on twig'
    color-bar:
      type: text
      label: 'Hex color of Skillset Bar'
    color-bar-opacity:
      type: integer
      label: 'Percent of Skillset Bar transparency'
    color-back:
      type: text
      label: 'Hex color of Skillset Backing'
    color-back-opacity:
      type: integer
      label: 'Percent of Skillset Backing transparency'
    color-border:
      type: text
      label: 'Hex color of Skillset Backing Border'
    color-labels:
      type: text
      label: 'Hex color of Skill Labels (dt) and Header (h3)'
    color-percent-inside:
      type: text
      label: 'Hex color of Skillset percent inside location'
    color-percent-outside:
      type: text
      label: 'Hex color of Skillset  percent inside location'
